### ISSUE TITLE
質問：今後実装する機能について

### ISSUE THREAD

**Issue by suminofu0829** [suminofu0829/tweet_fav_and_rt_count.app#11]
![2019-02-10 7 30 50](https://user-images.githubusercontent.com/43696401/52527060-d6013300-2d05-11e9-9cf3-f78962335a9e.png)

- 抽出したtweet.idがsince_id以降のものである場合、データベースにレコードを新規登録する。
- 
- tweet_time(tweetした日付・時刻)がファイルを実行する週(日曜0時から土曜23:59まで)であるtweetを取得
- tweet_point(お気に入りとRTの数の合計)が多い順に10個のtweetを取得
- viewに以下の項目を表示させる
1. 順位
1. ユーザー名
1. ツイート内容
1. ツイートした日時・時刻(リンク先に当該ツイートのURLを指定)
1. お気に入りの数
1. RTの数

**Comment by shoyan** [comment]
次の機能は不要だと思います。since_idを指定した場合、すでにデータベースに登録されているツイートは取得対象にならないためです。

> * 抽出したtweet.idがmax_id以前のものである場合、データベース登録済みのレコードを一度削除、再度新たにレコードを登録する。

表示する項目を具体的に教えてください。

> * viewにそれぞれ表示させる

**Comment by shoyan** [comment]
お気に入り数とRT数の更新の仕様も考えてみてください。
