### ISSUE TITLE
質問：mysql_update.rakeについて（お気に入りとRTの数の更新をする方法について）

### ISSUE THREAD

**Issue by suminofu0829** [suminofu0829/tweet_fav_and_rt_count.app#14]
[https://github.com/suminofu0829/tweet_fav_and_rt_count.app/pull/13](https://github.com/suminofu0829/tweet_fav_and_rt_count.app/pull/13)

mysql.rakeを実行することで新たなtweetをDBに追加することはできましたが
お気に入りとRTの数の更新機能の実装にかなり苦戦を強いられています。

先に変数last_tweetにテーブルの最後のレコードの要素を代入したあと
DB登録済みのデータは全削除し、
現時点で最新のtweetも含めて遡ってtwitterのリストから再度取得しなおして
tweetした日時の古い順からDBに登録し直す、ということをしています。
これをすればお気に入りとRTの数は更新されますが、
一度に取得できるデータが100数件と限られている為
データベースには常に100数件しか残らない状態となってしまいます。

データの更新をするメソッドとしてupdate、update_attributesなどを使おうとしたのですが
undefinedエラーとなってしまった為このような方法をとったのですが
他になにかいい方法はありますでしょうか？

**Comment by shoyan** [comment]
データを更新するには次の手順が必要です。
1. 更新対象のデータを取得する
1. 更新データを取得する
1. データを更新する

1つずつ考えていきましょう。

### 更新対象のデータを取得する
更新対象のデータはデータベースのtweetsテーブルより取得します。ここでは更新対象を7日間のツイートとして考えます。7日間のデータはtweets.created_atで条件を指定すれば取得できます。コードは次のような感じです（動作確認はしていないので動かないかもしれません）
```
tweets = Tweets.find_all(created_at: ">= #{Date.now.weeks_ago(1)}")
```

### 更新データを取得する
更新データはTwitterAPIから取得します。


since_idとmax_idを取得します。

```
since_id = tweets.first.tweet_id
max_id = tweets.last.tweet_id
```

あとは、since_idとmax_idを使ってタイムラインのツイートを取得します。
latest_tweets = タイムラインから取得するコード

### データを更新する
APIから取得したデータを元にデータベースのデータを更新していきます。

```
tweets.each do |tweet|
    latest_tweet = latest_tweetsからtweet.tweet_idに一致するツイートを取得する
    tweet.update(favorite_count: latest_tweet.favorite_count, retweet_count: latest_tweet.retweet_count)
end
```
