### ISSUE TITLE
質問：githubのコミット履歴の削除について

### ISSUE THREAD

**Issue by suminofu0829** [suminofu0829/tweet_fav_and_rt_count.app#17]
[https://github.com/suminofu0829/tweet_fav_and_rt_count.app/commit/3ff126eb636c08343fa68874e279ef5bbfd4da80](https://github.com/suminofu0829/tweet_fav_and_rt_count.app/commit/3ff126eb636c08343fa68874e279ef5bbfd4da80)
[https://github.com/suminofu0829/tweet_fav_and_rt_count.app/commit/772b5fa5227f39740f4cb6970334dfc849f9c96a](https://github.com/suminofu0829/tweet_fav_and_rt_count.app/commit/772b5fa5227f39740f4cb6970334dfc849f9c96a)
以前コミットした履歴にAPIのキーの情報が出てしまっているのですが
削除する方法はありますか？

**Comment by shoyan** [comment]
git rebaseを使って履歴を改変すれば削除できると思います。rebaseについてはこちらを参考にしてください。

* https://git-scm.com/book/ja/v1/Git-%E3%81%AE%E3%83%96%E3%83%A9%E3%83%B3%E3%83%81%E6%A9%9F%E8%83%BD-%E3%83%AA%E3%83%99%E3%83%BC%E3%82%B9
