### ISSUE TITLE
【質問】ページング後のランキングの表示について

### ISSUE THREAD

**Issue by suminofu0829** [suminofu0829/tweet_fav_and_rt_count.app#40]
ページネーション機能を実装しました。ランキングの表示が次ページでも１位から表示されるのですが、なにかいい方法はありますでしょうか？

**Comment by shoyan** [comment]
kaminariを使われているようなので、次のページを参照ください。
* https://qiita.com/nysalor/items/77b9d6bc5baa41ea01f3

**Comment by suminofu0829** [comment]
@shoyan きちんと表示できるようになりました！
