### ISSUE TITLE
【質問】tweet内容を全て表示させる方法について

### ISSUE THREAD

**Issue by suminofu0829** [suminofu0829/tweet_fav_and_rt_count.app#41]
データベースに登録する時点でtweetの内容が省略されているものがあるのですけれども
これを全て表示させる方法がわかりません。

以下のリンク先にはtweet_mode=extendedを指定するよう書かれているのですが
使い方がわからないので、もしお時間あればこちらも教えていただければありがたいです。

[Twitter の gem で 140 文字制限の拡張により正しくツイート情報が取得できない場合](https://obel.hatenablog.jp/entry/20170627/1498571659)

[140文字以上のツイートを取得する](https://qiita.com/hitsumabushi845/items/f7fd87106381fc65fc86)

**Comment by shoyan** [comment]
ドキュメントを調べてみましたが、tweet_modeの記載はありませんでした。
* https://developer.twitter.com/en/docs/accounts-and-users/create-manage-lists/api-reference/get-lists-statuses.html

Gemのoptionにもないようです。
* https://github.com/sferik/twitter/blob/844818cad07ce490ccb9d8542ebb6b4fc7a61cb4/lib/twitter/rest/lists.rb#L57-L60

現在のAPIには、tweet_mode=extendedは存在しないようです。

**Comment by shoyan** [comment]
PRはあるけど、マージはされていませんね。。
https://github.com/sferik/twitter/pull/848

**Comment by suminofu0829** [comment]
[tweet内容を省略せずに取得](https://github.com/suminofu0829/tweet_fav_and_rt_count.app/commit/f17408030b62cb3590a09992131cf9128ee6eba9)
tweet内容を全て取得できました！

**Comment by suminofu0829** [comment]
@shoyan 
[tweet内容を省略せずに取得](https://github.com/suminofu0829/tweet_fav_and_rt_count.app/commit/f17408030b62cb3590a09992131cf9128ee6eba9)
tweet内容を全て取得できました！
