### ISSUE TITLE
string型と思われるデータをsubメソッドで置換を試みたがエラーとなってしまった件

### ISSUE THREAD

**Issue by suminofu0829** [suminofu0829/tweet_fav_and_rt_count.app#72]
[Rakefile](https://github.com/suminofu0829/tweet_fav_and_rt_count.app/blob/master/lib/tasks/mysql.rake)で取得したプロフィール画像が粗かったので
サイズを変更する為[subメソッド](https://ref.xaio.jp/ruby/classes/string/sub)を使ってみました。

`user_image: tweet.user.profile_image_url.to_s.sub(/_normal/, '_400x400')`

上記のようにしたところ、うまくいったので現状問題ないのですが

元々は
[ドキュメント](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/user-object)を見てprofile_image_urlのデータ型がstringとなっていたので
`tweet.user.profile_image_url.sub(/_normal/, '_400x400')`
で実行したのですけれども
```
rake aborted!
NoMethodError: undefined method `sub' for #<Addressable::URI:0x00007ffe208f13c8>
```
未定義のメソッドです、とエラーが出てしまったのです。

なので、to_sメソッドでString型にしたうえで、文字列の置換をしたのですが
どうして、こうなったのかがわかりません。教えていただけますでしょうか？

**Comment by shoyan** [comment]
ドキュメントを確認する観点は素晴らしいです！しかし、残念ながら確認するドキュメントが違っているようです。こちらのドキュメントを確認してください。
* https://www.rubydoc.info/gems/twitter/Twitter/Profile#profile_image_url-instance_method

profile_image_urlの戻り値はAddressable::URIと書いてあります。[Addressable::URI](https://www.rubydoc.info/gems/addressable/Addressable/URI)のドキュメントを確認したところ、subメソッドは存在しません。よって、`undefined method`が発生します。
subはStringのメソッドなので、[to_sメソッド](https://www.rubydoc.info/gems/addressable/Addressable/URI#to_s-instance_method)でStringのメソッドに変換する必要があります。
