### ISSUE TITLE
質問：DB格納済である最新のtweet.idを実行の都度last_get_tweet_id の初期値として代入する方法について

### ISSUE THREAD

**Issue by suminofu0829** [suminofu0829/tweet_fav_and_rt_count.app#9]
```
namespace :mysql do
  desc "データベース(MySQL)にデータを登録するタスク"
  task add_data: :environment do
    class Tweet < ApplicationRecord

      require 'twitter'

      @client = Twitter::REST::Client.new do |config|
      end

      last_get_tweet_id = 1094181491335061504   #現時点では最新のtweet.idを仮に代入しているが、データベースに格納された最新tweetのidを代入できるようにしたい 
      @client.list_timeline("engineer", count:1000, since_id:last_get_tweet_id).each do |tweet| 
        unless tweet.retweet? 
          unless tweet.reply?
            if tweet.favorite_count > 0 || tweet.retweet_count > 0
              Tweet.create(tweet: tweet.full_text, user_name: tweet.user.screen_name, 
                           favorite_count: tweet.favorite_count, retweet_count: tweet.retweet_count, 
                           tweet_url: tweet.url, tweet_id: tweet.id, tweet_time: tweet.created_at)

                puts "最後に取得したTweetのid：#{last_get_tweet_id}"  #デバッグ用
            end
          end
        end
      end
    end
  end
end
```

**Comment by suminofu0829** [comment]
お疲れ様です。上記のようにmysql.rakeファイルを変更し



since_idを利用しようと試行錯誤しているのですが
リストから最後に取得したtweetのIDをlast_get_tweet_idという変数に代入後、
次回ファイル実行をする際の初期値とすることで、
既に格納済のtweetはデータベースに登録できないようにしたいと考えています。

一度mysql.rakeファイルを実行したところ
last_get_tweet_idが未定義となってしまった為、
仮のID(ファイル編集時点で最も新しいtweetのID)を
last_get_tweet_idの初期値として代入しているので
初期値として代入されたtweet.idより新しいものしか
データベースには登録されないようになりましたが
このままでは、毎回、last_get_tweet_idの初期値をファイル実行の都度入力する必要が生じます。

なので、データベースに格納された最も新しいtweet.idを
ファイル実行の都度last_get_tweet_id の初期値として代入できるようにしたいと
考えているのですが、その場合どうしたらよいでしょうか？？



※ちなみにtweet.idはレッスン中にデータベースのtweetテーブルにtweet.idカラムを作りましたが
ファイルを実行したときに
`ActiveModel::RangeError: 1094074574029901824 is out of range for ActiveModel::Type::Integer with limit 4 bytes`
と表示された為、sequelproをいじってデータ型をvarcharにしたところエラーが消えまして、tweet_time(tweetした日付時刻)というカラムも新たに追加しています。

また、レッスン中に
取得するリスト内のtweetは①RTされたtweetでないこと
という条件にしましたが、

②リプライではないこと
③お気に入りとRT数が０より大きいこと
という条件をさらに追加している状態です。

**Comment by shoyan** [comment]
> なので、データベースに格納された最も新しいtweet.idを
ファイル実行の都度last_get_tweet_id の初期値として代入できるようにしたいと
考えているのですが、その場合どうしたらよいでしょうか？？

`#last` メソッドを使って実装できるかと思います。
* https://railsguides.jp/active_record_querying.html#last

サンプルコードです。

```ruby
# 最後のtweetを取得する
last_tweet = Tweet.last
# tweet_idを取得
last_tweet_id = last_tweet.tweet_id
```

**Comment by shoyan** [comment]
> ③お気に入りとRT数が０より大きいこと
という条件をさらに追加している状態です。

お気に入りとRT数が0より大きいことだと0のtweetは登録されなくなりそうですが、大丈夫ですか？
登録時は0件ですが、お気に入り数とRT数の更新時に値が増えることはありそうだと思いました。

**Comment by suminofu0829** [comment]
@shoyan 

> お気に入りとRT数が0より大きいことだと0のtweetは登録されなくなりそうですが、大丈夫ですか？
> 登録時は0件ですが、お気に入り数とRT数の更新時に値が増えることはありそうだと思いました。

お気に入りとRT数が０より大きいという条件は削除しました。ありがとうございます。
